name: qiime2-2019.7
channels:
  - qiime2/label/r2019.7
  - ursky
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.1.5=h516909a_1002
  - arb-bio-tools=6.0.6=haa8b8d8_8
  - asn1crypto=0.24.0=py36_1003
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bibtexparser=1.1.0=py_0
  - binutils_impl_linux-64=2.31.1=h7fc9f1b_5
  - binutils_linux-64=2.31.1=h6176602_14
  - bioconductor-biobase=2.42.0=r351h14c3975_1
  - bioconductor-biocgenerics=0.28.0=r351_1
  - bioconductor-biocparallel=1.16.6=r351h1c2f66e_0
  - bioconductor-biostrings=2.50.2=r351h14c3975_0
  - bioconductor-dada2=1.10.0=r351hf484d3e_0
  - bioconductor-delayedarray=0.8.0=r351h14c3975_0
  - bioconductor-genomeinfodb=1.18.1=r351_0
  - bioconductor-genomeinfodbdata=1.2.1=r351_0
  - bioconductor-genomicalignments=1.18.1=r351h14c3975_0
  - bioconductor-genomicranges=1.34.0=r351h14c3975_0
  - bioconductor-iranges=2.16.0=r351h14c3975_0
  - bioconductor-rsamtools=1.34.0=r351hf484d3e_0
  - bioconductor-s4vectors=0.20.1=r351h14c3975_0
  - bioconductor-shortread=1.40.0=r351hf484d3e_0
  - bioconductor-summarizedexperiment=1.12.0=r351_0
  - bioconductor-xvector=0.22.0=r351h14c3975_0
  - bioconductor-zlibbioc=1.28.0=r351h14c3975_0
  - biom-format=2.1.7=py36hc1659b7_1002
  - blas=2.11=openblas
  - blast=2.9.0=pl526h3066fca_4
  - bleach=3.1.0=py_0
  - bokeh=1.3.1=py36_0
  - boost=1.68.0=py36h8619c78_1001
  - boost-cpp=1.68.0=h11c811c_1000
  - bwidget=1.9.11=1
  - bz2file=0.98=py_0
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2019.6.16=hecc5488_0
  - cachecontrol=0.12.5=py_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h8022711_0
  - chardet=3.0.4=py36h9880bd3_1008
  - click=7.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - conda=4.10.3=py36h5fab9bb_0
  - conda-package-handling=1.7.2=py36he6145b8_0
  - cryptography=2.7=py36h72c5cf5_0
  - curl=7.65.3=hf8cf82a_0
  - cutadapt=2.4=py36h14c3975_0
  - cycler=0.10.0=py_2
  - cython=0.29.21=py36ha357f81_1
  - dbus=1.13.6=he372182_0
  - deblur=1.1.0=py_1
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - dnaio=0.3=py36h14c3975_1
  - emperor=1.0.0b19=py36_0
  - entrez-direct=13.9=pl5262he881be0_2
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.5=he1b5a44_1004
  - fastcluster=1.1.25=py36hb3f55d8_1000
  - fasttree=2.1.10=0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he06d7ca_2
  - future=0.17.1=py36_1000
  - gcc_impl_linux-64=7.3.0=hd420e75_5
  - gcc_linux-64=7.3.0=h553295d_14
  - gettext=0.19.8.1=hf34092f_1004
  - gfortran_impl_linux-64=7.3.0=hdf63c60_5
  - gfortran_linux-64=7.3.0=h553295d_14
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gneiss=0.4.5=py_0
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.5=h294904e_1
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_5
  - gxx_linux-64=7.3.0=h553295d_14
  - h5py=2.9.0=nompi_py36hcafd542_1103
  - harfbuzz=2.4.0=h37c48d4_1
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - hdmedians=0.13=py36h785e9b2_1002
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py36_1000
  - ijson=2.3=py_1
  - importlib_metadata=0.18=py36_0
  - ipykernel=5.1.1=py36h5ca1d4c_0
  - ipython=7.7.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - iqtree=1.6.11.1=he513fc3_0
  - jedi=0.14.1=py36_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.1.0=py36hdb11119_1
  - krb5=1.16.3=h05b26f9_1001
  - lcms2=2.9=h2e4bb80_0
  - libarbdb=6.0.6=haa8b8d8_8
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libcurl=7.65.3=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=11_openblas
  - liblapacke=3.8.0=11_openblas
  - libopenblas=0.3.6=h6e990d7_6
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.17=h516909a_0
  - libsolv=0.7.16=h8b12597_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - lockfile=0.12.2=py_1
  - lz4-c=1.8.3=he1b5a44_1001
  - mafft=7.310=he1b5a44_3
  - make=4.2.1=h14c3975_2004
  - mamba=0.1.2=py36hdb11119_0
  - markupsafe=1.1.1=py36he6145b8_2
  - mistune=0.8.4=py36h1d69622_1002
  - more-itertools=7.2.0=py_0
  - msgpack-python=0.6.1=py36h6bb024c_0
  - natsort=6.0.0=py_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.3=py_0
  - nose=1.3.7=py_1006
  - notebook=6.0.0=py36_0
  - numpy=1.17.0=py36h95a1406_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjdk=11.0.1=h600c080_1018
  - openssl=1.1.1c=h516909a_0
  - packaging=19.0=py_0
  - pandas=0.24.2=py36hb3f55d8_1
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - pango=1.40.14=he7ab937_1005
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=he1b5a44_1004
  - perl=5.26.2=h36c2ea0_1008
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-base=2.23=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.086=pl526hf484d3e_0
  - perl-compress-raw-zlib=2.086=pl526h6bb024c_1
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tree=5.07=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-io-compress=2.086=pl526hf484d3e_0
  - perl-io-html=1.001=pl526_2
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-libwww-perl=6.39=pl526_0
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-mime-base64=3.15=pl526_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-parent=0.236=pl526_1
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.50=pl526h14c3975_0
  - perl-socket=2.027=pl526_1
  - perl-storable=3.15=pl526h14c3975_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-time-local=1.28=pl526_1
  - perl-try-tiny=0.30=pl526_1
  - perl-types-serialiser=1.0=pl526_2
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44_01=pl526ha1d75be_1002
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-simple=2.25=pl526_1
  - perl-xsloader=0.24=pl526_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py_1003
  - pigz=2.3.4=hed695b0_1
  - pip=19.2.1=py36_0
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.12.0=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - psutil=5.6.3=py36h516909a_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.8.0=py_0
  - pycosat=0.6.3=py36he6145b8_1005
  - pycparser=2.19=py_2
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.3.0=py_0
  - pyqt=5.9.2=py36hcca6a23_4
  - pyrsistent=0.15.4=py36h516909a_0
  - pysocks=1.7.0=py36_0
  - pytest=5.0.1=py36_1
  - python=3.6.7=h357f687_1005
  - python-dateutil=2.8.0=py_0
  - python_abi=3.6=2_cp36m
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py36h516909a_0
  - pyzmq=18.0.2=py36h1768529_2
  - q2-alignment=2019.7.0=py36_0
  - q2-composition=2019.7.0=py36_0
  - q2-cutadapt=2019.7.0=py36_0
  - q2-dada2=2019.7.0=py36_0
  - q2-deblur=2019.7.0=py36_0
  - q2-demux=2019.7.0=py36_0
  - q2-diversity=2019.7.0=py36_0
  - q2-emperor=2019.7.0=py36_0
  - q2-feature-classifier=2019.7.0=py36_0
  - q2-feature-table=2019.7.0=py36_0
  - q2-fragment-insertion=2019.7.0=py36_0
  - q2-gneiss=2019.7.0=py36_0
  - q2-longitudinal=2019.7.0=py36_0
  - q2-metadata=2019.7.0=py36_0
  - q2-phylogeny=2019.7.0=py36_0
  - q2-quality-control=2019.7.0=py36_0
  - q2-quality-filter=2019.7.0=py36_0
  - q2-sample-classifier=2019.7.1=py36_0
  - q2-taxa=2019.7.0=py36_0
  - q2-types=2019.7.0=py36_0
  - q2-vsearch=2019.7.0=py36_0
  - q2cli=2019.7.0=py36_0
  - q2templates=2019.7.0=py36_0
  - qiime2=2019.7.0=py36_0
  - qt=5.9.7=h52cfd70_2
  - r-assertthat=0.2.1=r35h6115d3f_1
  - r-backports=1.1.4=r35hcdcec82_1
  - r-base=3.5.1=h08e1455_1008
  - r-bh=1.69.0_1=r35h6115d3f_1
  - r-bitops=1.0_6=r35hcdcec82_1003
  - r-cli=1.1.0=r35h6115d3f_2
  - r-cluster=2.1.0=r35h9bbef5b_2
  - r-colorspace=1.4_1=r35hcdcec82_1
  - r-crayon=1.3.4=r35h6115d3f_1002
  - r-data.table=1.12.2=r35hcdcec82_1
  - r-digest=0.6.20=r35h0357c0b_1
  - r-ellipsis=0.2.0.1=r35hcdcec82_1
  - r-fansi=0.4.0=r35hcdcec82_1001
  - r-formatr=1.7=r35h6115d3f_1
  - r-futile.logger=1.4.3=r35h6115d3f_1002
  - r-futile.options=1.0.1=r35h6115d3f_1001
  - r-ggplot2=3.2.0=r35h6115d3f_1
  - r-glue=1.3.1=r35hcdcec82_1
  - r-gtable=0.3.0=r35h6115d3f_2
  - r-hwriter=1.3.2=r35h6115d3f_1002
  - r-labeling=0.3=r35h6115d3f_1002
  - r-lambda.r=1.2.3=r35h6115d3f_1001
  - r-lattice=0.20_38=r35hcdcec82_1002
  - r-latticeextra=0.6_28=r35h6115d3f_1002
  - r-lazyeval=0.2.2=r35hcdcec82_1
  - r-magrittr=1.5=r35h6115d3f_1002
  - r-mass=7.3_51.4=r35hcdcec82_1
  - r-matrix=1.2_17=r35hcdcec82_1
  - r-matrixstats=0.54.0=r35hcdcec82_1001
  - r-mgcv=1.8_28=r35hcdcec82_1
  - r-munsell=0.5.0=r35h6115d3f_1002
  - r-nlme=3.1_140=r35h9bbef5b_1
  - r-permute=0.9_5=r35h6115d3f_2
  - r-pillar=1.4.2=r35h6115d3f_2
  - r-pkgconfig=2.0.2=r35h6115d3f_1003
  - r-plyr=1.8.4=r35h0357c0b_1003
  - r-r6=2.4.0=r35h6115d3f_2
  - r-rcolorbrewer=1.1_2=r35h6115d3f_1002
  - r-rcpp=1.0.2=r35h0357c0b_0
  - r-rcppparallel=4.4.3=r35h0357c0b_2
  - r-rcurl=1.95_4.12=r35hcdcec82_1
  - r-reshape2=1.4.3=r35h0357c0b_1004
  - r-rlang=0.4.0=r35hcdcec82_1
  - r-scales=1.0.0=r35h0357c0b_1002
  - r-snow=0.4_3=r35h6115d3f_1001
  - r-stringi=1.4.3=r35h0357c0b_2
  - r-stringr=1.4.0=r35h6115d3f_1
  - r-tibble=2.1.3=r35hcdcec82_1
  - r-utf8=1.1.4=r35hcdcec82_1002
  - r-vctrs=0.2.0=r35hcdcec82_1
  - r-vegan=2.5_5=r35h9bbef5b_2
  - r-viridislite=0.3.0=r35h6115d3f_1002
  - r-withr=2.1.2=r35h6115d3f_1001
  - r-zeallot=0.1.0=r35h6115d3f_1001
  - raxml=8.2.12=h516909a_2
  - readline=8.0=h46ee950_1
  - requests=2.22.0=py36_1
  - ruamel_yaml=0.15.71=py36h14c3975_1000
  - scikit-bio=0.5.5=py36h3010b51_1000
  - scikit-learn=0.21.2=py36hcdab131_1
  - scipy=1.3.0=py36h921218d_1
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py36_0
  - sina=1.6.0=hc7f9b0f_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1001
  - sortmerna=2.0=he860b03_4
  - sqlite=3.29.0=hcee41ef_1
  - statsmodels=0.10.1=py36hc1659b7_2
  - tbb=2019.7=hc9558a2_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=hed695b0_1003
  - tktable=2.10=h555a92e_3
  - tornado=6.0.3=py36h516909a_4
  - traitlets=4.3.2=py36_1000
  - tzlocal=2.0.0=py_0
  - unifrac=0.10.0=py36h6bb024c_1
  - urllib3=1.25.3=py36_0
  - vsearch=2.7.0=1
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.5.1=py36h5fab9bb_4
  - xopen=0.7.3=py_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h516909a_1002
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zipp=0.5.1=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.0=h3b9ef0a_0
  - pip:
    - absl-py==0.13.0
    - adjusttext==0.7.3
    - astor==0.8.1
    - dataclasses==0.8
    - gast==0.2.2
    - gemelli==0.0.6
    - google-pasta==0.2.0
    - grpcio==1.39.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - lxml==4.6.3
    - markdown==3.3.4
    - matplotlib==3.3.4
    - mmvec==1.0.6
    - opt-einsum==3.3.0
    - pillow==8.4.0
    - protobuf==3.17.3
    - pybind11==2.8.1
    - seaborn==0.11.2
    - tensorboard==1.15.0
    - tensorflow==1.15.5
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - tqdm==4.62.0
    - werkzeug==2.0.1
    - wrapt==1.12.1
prefix: /home/cmartino/.conda/envs/qiime2-2019.7
